import { defineConfig } from 'vite'
import path from 'path'
import fs from 'fs'

export default defineConfig(({ command, mode }) => {
  // Prevent inline dev: force external launcher to set EXTERNAL_START=1
  if (command === 'serve' && process.env.EXTERNAL_START !== '1') {
    throw new Error('Inline dev server is FORBIDDEN. Use ./scripts/start-vite.ps1 -Port 5173 -Https')
  }

  console.log('[STEP 21] HTTPS with working certificates - bypassing HTTP issues')
  
  // Try PFX format first (generated by original script), then fall back to PEM
  const pfxPath = path.resolve(__dirname, '../certs/local.lchaty.com.pfx')
  const certPath = path.resolve(__dirname, '../certs/local.lchaty.com+1.pem')
  const keyPath = path.resolve(__dirname, '../certs/local.lchaty.com+1-key.pem')
  
  let https: any = false
  
  // Try PFX first (fresh generated)
  if (fs.existsSync(pfxPath)) {
    console.log('[HTTPS] Loading PFX certificate:', pfxPath)
    https = {
      pfx: fs.readFileSync(pfxPath),
      passphrase: process.env.DEV_CERT_PASSPHRASE || 'changeit'
    }
    console.log('[HTTPS] PFX certificate loaded successfully')
  } 
  // Fall back to PEM if PFX not available
  else if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
    console.log('[HTTPS] Loading PEM certificates:', certPath)
    https = {
      cert: fs.readFileSync(certPath),
      key: fs.readFileSync(keyPath)
    }
    console.log('[HTTPS] PEM certificates loaded successfully')
  } else {
    console.log('[HTTPS] No certificates found, using HTTP')
  }
  
  return {
    root: path.resolve(__dirname),
    base: '/',
    build: {
      outDir: 'dist',
      rollupOptions: {
        input: {
          main: path.resolve(__dirname, 'index.html'),
          admin: path.resolve(__dirname, 'admin.html')
        }
      }
    },
    server: {
      https,
      port: 5173,
      host: '0.0.0.0',  // Bind to all interfaces for HTTPS
      strictPort: true,
      proxy: {
        '/api': {
          target: 'https://chat-backend.lchaty.com',
          changeOrigin: true,
          secure: true,
          cookieDomainRewrite: { '*': 'local.lchaty.com' },
          cookiePathRewrite: { '*': '/' }
        },
        '/api/auth': {
          target: 'https://chat-backend.lchaty.com',
          changeOrigin: true,
          secure: true,
          cookieDomainRewrite: { '*': 'local.admin.lchaty.com' },
          cookiePathRewrite: { '*': '/' }
        }
      }
    }
  }
})
